sonar.projectKey=STAGINGSQRATest_demo-shop
sonar.organization=stagingsqratest
sonar.projectName=Demo Shop
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx
sonar.sourceEncoding=UTF-8
